name: Pipeline

on: [push,workflow_dispatch]

jobs:
  BUILD:
    uses: earnestdl/templates/.github/workflows/build.yml@main
    with: 
      appType: bash
      appVersion: 0
      
  DEV:
    needs: BUILD
    uses: earnestdl/templates/.github/workflows/deploy.yml@main
    with: 
      deployTarget: openshift
      deployEnvironment: dev
      deployRegions: "['east', 'metro']" 
    secrets:
      TOKEN_E1: ${{ secrets.TOKEN_E1_DEV }}
      TOKEN_E2: ${{ secrets.TOKEN_E2_DEV }}

  QA:
    needs: DEV
    uses: earnestdl/templates/.github/workflows/deploy.yml@main
    with: 
      deployTarget: openshift
      deployEnvironment: qa
      deployRegions: "['east', 'metro']" 
    secrets:
      TOKEN_E1: ${{ secrets.TOKEN_E1_QA }}
      TOKEN_E2: ${{ secrets.TOKEN_E2_QA }}

  STRESS:
    needs: QA
    uses: earnestdl/templates/.github/workflows/deploy.yml@main
    with: 
      deployTarget: openshift
      deployEnvironment: stress
      deployRegions: "['east', 'metro']" 
    secrets:
      TOKEN_E1: ${{ secrets.TOKEN_E1_QA }}
      TOKEN_E2: ${{ secrets.TOKEN_E2_QA }}

  PROD:
    needs: STRESS
    uses: earnestdl/templates/.github/workflows/deploy.yml@main
    with: 
      deployTarget: openshift
      deployEnvironment: prod
      deployRegions: "['east', 'metro']" 
    secrets:
      TOKEN_E1: ${{ secrets.TOKEN_E1_PROD }}
      TOKEN_E2: ${{ secrets.TOKEN_E2_PROD }}
